---
- name: Install dev tools
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_dev_tools }}"

- name: Install virtualization tools
  dnf:
    name: "@virtualization"
    state: latest
