---
- name: Install pip
  become_user: root
  dnf:
    name: python3-pip
    state: latest
# - name: Install base pip apps
#   become_user: "{{ ansible_user }}"
#   pip:
#     name: "{{ pip_base_apps }}"
#     extra_args: --user
