---
- name: Create folder for python venvs
  file:
    path: "/home/{{ ansible_user }}/Documents/python_venvs/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0750

- name: Install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -
  changed_when: false
  become_user: "{{ ansible_user }}"
  tags:
    - dev
