---
- name: Install texlive
  dnf:
    name:
      - texlive-collection-latex
      - texlive-collection-xetex
      - texlive-collection-latexrecommended
      - texlive-collection-langenglish
      - texlive-collection-langczechslovak
    state: latest

- name: Install texmaker
  dnf:
    name: texmaker
    state: latest
